# Generated by Django 4.2.2 on 2023-08-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='more_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='images/')),
                ('identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folioappp.identifier')),
            ],
        ),
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag', models.CharField(max_length=100)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_acquired', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='testimonial_images')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(blank=True, max_length=50, null=True)),
                ('categoryapp', models.CharField(blank=True, max_length=50, null=True)),
                ('categoryweb', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='images')),
                ('identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folioappp.identifier')),
                ('pictures', models.ManyToManyField(to='folioappp.more_image')),
            ],
        ),
        migrations.CreateModel(
            name='professional_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(max_length=200)),
                ('skill', models.ManyToManyField(to='folioappp.skill')),
            ],
        ),
        migrations.CreateModel(
            name='employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_address', models.CharField(max_length=200, null=True)),
                ('responsibility', models.ManyToManyField(to='folioappp.responsibility')),
            ],
        ),
    ]
