# Generated by Django 4.2.2 on 2023-08-24 14:35

from django.db import migrations
import folioappp.models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=folioappp.models.AzureBlobImageField(upload_to='media'),
        ),
    ]
