# Generated by Django 4.2.2 on 2023-08-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='images')),
                ('identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folioappp.identifier')),
                ('pictures', models.ManyToManyField(to='folioappp.more_image')),
            ],
        ),
    ]
