# Generated by Django 4.2.2 on 2023-06-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employment',
            name='responsibility',
        ),
        migrations.AddField(
            model_name='employment',
            name='responsibility',
            field=models.ManyToManyField(to='folioappp.responsibility'),
        ),
    ]
