# Generated by Django 4.2.2 on 2023-08-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='categoryapp',
        ),
        migrations.AddField(
            model_name='project',
            name='categoryweb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
