# Generated by Django 4.2.2 on 2023-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='codebank',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
