# Generated by Django 4.2.2 on 2023-06-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0002_responsibility_remove_employment_responsibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='about',
            field=models.CharField(max_length=200),
        ),
    ]
