# Generated by Django 4.2.2 on 2023-08-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0002_project1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project1',
        ),
    ]
