# Generated by Django 4.2.2 on 2023-08-24 15:23

from django.db import migrations, models
import folioappp.models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more_image',
            name='picture',
            field=models.ImageField(storage=folioappp.models.MyAzureStorage(), upload_to='image'),
        ),
    ]
