# Generated by Django 4.2.2 on 2023-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0003_alter_qualification_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='duty',
            field=models.CharField(max_length=200),
        ),
    ]
