# Generated by Django 4.2.2 on 2023-06-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0004_alter_responsibility_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
