# Generated by Django 4.2.2 on 2023-06-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0005_alter_qualification_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_acquired', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='professional_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag', models.CharField(max_length=200)),
                ('year', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(max_length=200)),
                ('skill', models.ManyToManyField(to='folioappp.skill')),
            ],
        ),
    ]
