# Generated by Django 4.2.2 on 2023-06-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0006_skill_professional_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='current',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='professional_course',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='still_studying',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
