# Generated by Django 4.2.2 on 2023-06-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0007_alter_employment_current_alter_employment_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='current',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
