# Generated by Django 4.2.2 on 2023-06-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0009_alter_employment_current_alter_employment_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='start_date',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='still_studying',
        ),
    ]
