# Generated by Django 4.2.2 on 2023-06-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0010_rename_start_date_qualification_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='current',
        ),
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
