# Generated by Django 4.2.2 on 2023-06-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0011_remove_employment_current_alter_employment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_acquired',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
