# Generated by Django 4.2.2 on 2023-06-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0013_alter_professional_course_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_course',
            name='skill',
            field=models.ManyToManyField(to='folioappp.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_acquired',
            field=models.CharField(max_length=200),
        ),
    ]
