# Generated by Django 4.2.2 on 2023-07-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0016_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
