# Generated by Django 4.2.2 on 2023-07-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0017_testimonial_organization_alter_testimonial_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='picture',
            new_name='image',
        ),
    ]
