# Generated by Django 4.2.2 on 2023-07-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0018_rename_picture_testimonial_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='image',
            new_name='picture',
        ),
    ]
