# Generated by Django 4.2.2 on 2023-08-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0020_alter_testimonial_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='more_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='pictures',
            field=models.ManyToManyField(to='folioappp.more_image'),
        ),
    ]
