# Generated by Django 4.2.2 on 2023-08-14 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folioappp', '0021_more_image_project_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='more_image',
            name='title',
            field=models.CharField(default=datetime.datetime(2023, 8, 14, 13, 25, 55, 571120, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='more_image',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folioappp.identifier'),
        ),
        migrations.AddField(
            model_name='project',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folioappp.identifier'),
        ),
    ]
